import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="container mt-5">
      <Head>
        <title>IM Query App</title>
        <meta name="description" content="Generated by Manish for IndiaMART" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='text-center mb-5'>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Click on the following Link View Product {' '}
        </p>
        <Link href="/products/1" prefetch={false}>Brazilian Coffee</Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
